import Head from "next/head"
import { Spotify } from "components/icons"
import { motion } from "framer-motion"

export default function Home() {
	return (
		<>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="p-20 flex gap-10 flex-col">
				<header className="flex flex-col gap-4">
					<Spotify className="w-40" />
				</header>
				<motion.div
					initial={{ x: 100, opacity: 0 }}
					animate={{ x: 0, opacity: 1 }}
					className="px-3 py-1 rounded-full bg-red-500 font-medium max-w-max text-white"
				>
					Playlist
				</motion.div>
			</main>
		</>
	)
}
